version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "9002:9002"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: baconpancakes
      DB_NAME: example_db
      NODE_ENV: development
      PORT: 9002